/* Themed word lists. Every word has an emoji used as the picture clue
   and a Ukrainian translation. Pictures are rendered from Twemoji
   (CC-BY 4.0) with the native emoji as a fallback. */

const THEMES = [
  {
    id: 'fruits', name: 'Fruits', icon: '🍎', color: '#f4511e',
    words: [
      { w: 'apple', e: '🍎', u: 'яблуко' },
      { w: 'banana', e: '🍌', u: 'банан' },
      { w: 'grapes', e: '🍇', u: 'виноград' },
      { w: 'watermelon', e: '🍉', u: 'кавун' },
      { w: 'lemon', e: '🍋', u: 'лимон' },
      { w: 'orange', e: '🍊', u: 'апельсин' },
      { w: 'strawberry', e: '🍓', u: 'полуниця' },
      { w: 'cherry', e: '🍒', u: 'вишня' },
      { w: 'peach', e: '🍑', u: 'персик' },
      { w: 'pear', e: '🍐', u: 'груша' },
      { w: 'pineapple', e: '🍍', u: 'ананас' },
      { w: 'kiwi', e: '🥝', u: 'ківі' },
      { w: 'mango', e: '🥭', u: 'манго' },
      { w: 'coconut', e: '🥥', u: 'кокос' },
      { w: 'blueberry', e: '🫐', u: 'чорниця' },
    ],
  },
  {
    id: 'vegetables', name: 'Vegetables', icon: '🥕', color: '#43a047',
    words: [
      { w: 'carrot', e: '🥕', u: 'морква' },
      { w: 'corn', e: '🌽', u: 'кукурудза' },
      { w: 'tomato', e: '🍅', u: 'помідор' },
      { w: 'eggplant', e: '🍆', u: 'баклажан' },
      { w: 'potato', e: '🥔', u: 'картопля' },
      { w: 'broccoli', e: '🥦', u: 'броколі' },
      { w: 'cucumber', e: '🥒', u: 'огірок' },
      { w: 'pepper', e: '🫑', u: 'перець' },
      { w: 'onion', e: '🧅', u: 'цибуля' },
      { w: 'garlic', e: '🧄', u: 'часник' },
      { w: 'mushroom', e: '🍄', u: 'гриб' },
      { w: 'pumpkin', e: '🎃', u: 'гарбуз' },
      { w: 'avocado', e: '🥑', u: 'авокадо' },
      { w: 'olive', e: '🫒', u: 'оливка' },
    ],
  },
  {
    id: 'animals', name: 'Animals', icon: '🦁', color: '#fb8c00',
    words: [
      { w: 'dog', e: '🐶', u: 'собака' },
      { w: 'cat', e: '🐱', u: 'кіт' },
      { w: 'lion', e: '🦁', u: 'лев' },
      { w: 'tiger', e: '🐯', u: 'тигр' },
      { w: 'elephant', e: '🐘', u: 'слон' },
      { w: 'monkey', e: '🐵', u: 'мавпа' },
      { w: 'rabbit', e: '🐰', u: 'кролик' },
      { w: 'bear', e: '🐻', u: 'ведмідь' },
      { w: 'fox', e: '🦊', u: 'лисиця' },
      { w: 'panda', e: '🐼', u: 'панда' },
      { w: 'pig', e: '🐷', u: 'свиня' },
      { w: 'cow', e: '🐮', u: 'корова' },
      { w: 'horse', e: '🐴', u: 'кінь' },
      { w: 'sheep', e: '🐑', u: 'вівця' },
      { w: 'chicken', e: '🐔', u: 'курка' },
      { w: 'penguin', e: '🐧', u: 'пінгвін' },
      { w: 'frog', e: '🐸', u: 'жаба' },
      { w: 'whale', e: '🐳', u: 'кит' },
      { w: 'dolphin', e: '🐬', u: 'дельфін' },
      { w: 'snake', e: '🐍', u: 'змія' },
      { w: 'turtle', e: '🐢', u: 'черепаха' },
      { w: 'owl', e: '🦉', u: 'сова' },
      { w: 'zebra', e: '🦓', u: 'зебра' },
      { w: 'giraffe', e: '🦒', u: 'жираф' },
      { w: 'duck', e: '🦆', u: 'качка' },
      { w: 'fish', e: '🐟', u: 'риба' },
      { w: 'octopus', e: '🐙', u: 'восьминіг' },
      { w: 'butterfly', e: '🦋', u: 'метелик' },
      { w: 'bee', e: '🐝', u: 'бджола' },
      { w: 'koala', e: '🐨', u: 'коала' },
    ],
  },
  {
    id: 'food', name: 'Food', icon: '🍕', color: '#e53935',
    words: [
      { w: 'bread', e: '🍞', u: 'хліб' },
      { w: 'cheese', e: '🧀', u: 'сир' },
      { w: 'egg', e: '🥚', u: 'яйце' },
      { w: 'pizza', e: '🍕', u: 'піца' },
      { w: 'cake', e: '🍰', u: 'торт' },
      { w: 'cookie', e: '🍪', u: 'печиво' },
      { w: 'milk', e: '🥛', u: 'молоко' },
      { w: 'honey', e: '🍯', u: 'мед' },
      { w: 'rice', e: '🍚', u: 'рис' },
      { w: 'soup', e: '🍲', u: 'суп' },
      { w: 'salad', e: '🥗', u: 'салат' },
      { w: 'sandwich', e: '🥪', u: 'бутерброд' },
      { w: 'popcorn', e: '🍿', u: 'попкорн' },
      { w: 'chocolate', e: '🍫', u: 'шоколад' },
      { w: 'donut', e: '🍩', u: 'пончик' },
      { w: 'hamburger', e: '🍔', u: 'гамбургер' },
      { w: 'fries', e: '🍟', u: 'картопля фрі' },
      { w: 'hotdog', e: '🌭', u: 'хот-дог' },
      { w: 'taco', e: '🌮', u: 'тако' },
      { w: 'pancakes', e: '🥞', u: 'млинці' },
      { w: 'croissant', e: '🥐', u: 'круасан' },
      { w: 'pretzel', e: '🥨', u: 'крендель' },
      { w: 'bacon', e: '🥓', u: 'бекон' },
    ],
  },
  {
    id: 'kitchen', name: 'Kitchen', icon: '🍳', color: '#00897b',
    words: [
      { w: 'knife', e: '🔪', u: 'ніж' },
      { w: 'spoon', e: '🥄', u: 'ложка' },
      { w: 'plate', e: '🍽️', u: 'тарілка' },
      { w: 'bowl', e: '🥣', u: 'миска' },
      { w: 'cup', e: '☕', u: 'чашка' },
      { w: 'glass', e: '🥛', u: 'склянка' },
      { w: 'teapot', e: '🫖', u: 'чайник' },
      { w: 'pan', e: '🍳', u: 'сковорода' },
      { w: 'salt', e: '🧂', u: 'сіль' },
      { w: 'jar', e: '🫙', u: 'банка' },
      { w: 'chopsticks', e: '🥢', u: 'палички для їжі' },
    ],
  },
  {
    id: 'home', name: 'Home', icon: '🛋️', color: '#8e24aa',
    words: [
      { w: 'bed', e: '🛏️', u: 'ліжко' },
      { w: 'chair', e: '🪑', u: 'стілець' },
      { w: 'couch', e: '🛋️', u: 'диван' },
      { w: 'door', e: '🚪', u: 'двері' },
      { w: 'window', e: '🪟', u: 'вікно' },
      { w: 'lamp', e: '💡', u: 'лампа' },
      { w: 'key', e: '🔑', u: 'ключ' },
      { w: 'toilet', e: '🚽', u: 'туалет' },
      { w: 'bathtub', e: '🛁', u: 'ванна' },
      { w: 'soap', e: '🧼', u: 'мило' },
      { w: 'broom', e: '🧹', u: 'мітла' },
      { w: 'basket', e: '🧺', u: 'кошик' },
      { w: 'candle', e: '🕯️', u: 'свічка' },
      { w: 'mirror', e: '🪞', u: 'дзеркало' },
      { w: 'clock', e: '⏰', u: 'годинник' },
      { w: 'television', e: '📺', u: 'телевізор' },
      { w: 'telephone', e: '☎️', u: 'телефон' },
    ],
  },
  {
    id: 'clothes', name: 'Clothes', icon: '👕', color: '#1e88e5',
    words: [
      { w: 'shirt', e: '👕', u: 'сорочка' },
      { w: 'dress', e: '👗', u: 'сукня' },
      { w: 'shoe', e: '👟', u: 'кросівок' },
      { w: 'cap', e: '🧢', u: 'кепка' },
      { w: 'hat', e: '👒', u: 'капелюх' },
      { w: 'sock', e: '🧦', u: 'шкарпетка' },
      { w: 'scarf', e: '🧣', u: 'шарф' },
      { w: 'gloves', e: '🧤', u: 'рукавички' },
      { w: 'coat', e: '🧥', u: 'пальто' },
      { w: 'jeans', e: '👖', u: 'джинси' },
      { w: 'boot', e: '👢', u: 'чобіт' },
      { w: 'crown', e: '👑', u: 'корона' },
      { w: 'glasses', e: '👓', u: 'окуляри' },
      { w: 'ring', e: '💍', u: 'каблучка' },
      { w: 'shorts', e: '🩳', u: 'шорти' },
      { w: 'sandal', e: '👡', u: 'босоніжка' },
    ],
  },
  {
    id: 'transport', name: 'Transport', icon: '🚗', color: '#3949ab',
    words: [
      { w: 'car', e: '🚗', u: 'машина' },
      { w: 'bus', e: '🚌', u: 'автобус' },
      { w: 'train', e: '🚆', u: 'поїзд' },
      { w: 'plane', e: '✈️', u: 'літак' },
      { w: 'ship', e: '🚢', u: 'корабель' },
      { w: 'bicycle', e: '🚲', u: 'велосипед' },
      { w: 'rocket', e: '🚀', u: 'ракета' },
      { w: 'helicopter', e: '🚁', u: 'гелікоптер' },
      { w: 'taxi', e: '🚕', u: 'таксі' },
      { w: 'truck', e: '🚚', u: 'вантажівка' },
      { w: 'tractor', e: '🚜', u: 'трактор' },
      { w: 'boat', e: '⛵', u: 'човен' },
      { w: 'scooter', e: '🛴', u: 'самокат' },
      { w: 'motorcycle', e: '🏍️', u: 'мотоцикл' },
      { w: 'ambulance', e: '🚑', u: 'швидка допомога' },
      { w: 'canoe', e: '🛶', u: 'каное' },
    ],
  },
  {
    id: 'school', name: 'School', icon: '🎒', color: '#d81b60',
    words: [
      { w: 'book', e: '📖', u: 'книга' },
      { w: 'pencil', e: '✏️', u: 'олівець' },
      { w: 'pen', e: '🖊️', u: 'ручка' },
      { w: 'scissors', e: '✂️', u: 'ножиці' },
      { w: 'ruler', e: '📏', u: 'лінійка' },
      { w: 'backpack', e: '🎒', u: 'рюкзак' },
      { w: 'globe', e: '🌍', u: 'глобус' },
      { w: 'computer', e: '💻', u: "комп'ютер" },
      { w: 'clock', e: '⏰', u: 'годинник' },
      { w: 'bell', e: '🔔', u: 'дзвоник' },
      { w: 'notebook', e: '📓', u: 'зошит' },
      { w: 'crayon', e: '🖍️', u: 'восковий олівець' },
      { w: 'paperclip', e: '📎', u: 'скріпка' },
      { w: 'magnet', e: '🧲', u: 'магніт' },
      { w: 'microscope', e: '🔬', u: 'мікроскоп' },
      { w: 'calendar', e: '📅', u: 'календар' },
    ],
  },
  {
    id: 'body', name: 'My Body', icon: '👀', color: '#6d4c41',
    words: [
      { w: 'eye', e: '👁️', u: 'око' },
      { w: 'ear', e: '👂', u: 'вухо' },
      { w: 'nose', e: '👃', u: 'ніс' },
      { w: 'mouth', e: '👄', u: 'рот' },
      { w: 'hand', e: '✋', u: 'долоня' },
      { w: 'foot', e: '🦶', u: 'ступня' },
      { w: 'leg', e: '🦵', u: 'нога' },
      { w: 'tooth', e: '🦷', u: 'зуб' },
      { w: 'brain', e: '🧠', u: 'мозок' },
      { w: 'bone', e: '🦴', u: 'кістка' },
      { w: 'tongue', e: '👅', u: 'язик' },
      { w: 'arm', e: '💪', u: 'рука' },
      { w: 'heart', e: '🫀', u: 'серце' },
    ],
  },
  {
    id: 'nature', name: 'Nature', icon: '🌈', color: '#039be5',
    words: [
      { w: 'sun', e: '☀️', u: 'сонце' },
      { w: 'moon', e: '🌙', u: 'місяць' },
      { w: 'star', e: '⭐', u: 'зірка' },
      { w: 'cloud', e: '☁️', u: 'хмара' },
      { w: 'rain', e: '🌧️', u: 'дощ' },
      { w: 'snow', e: '❄️', u: 'сніг' },
      { w: 'rainbow', e: '🌈', u: 'веселка' },
      { w: 'tree', e: '🌳', u: 'дерево' },
      { w: 'flower', e: '🌸', u: 'квітка' },
      { w: 'leaf', e: '🍁', u: 'листок' },
      { w: 'mountain', e: '⛰️', u: 'гора' },
      { w: 'volcano', e: '🌋', u: 'вулкан' },
      { w: 'wave', e: '🌊', u: 'хвиля' },
      { w: 'fire', e: '🔥', u: 'вогонь' },
      { w: 'lightning', e: '⚡', u: 'блискавка' },
      { w: 'cactus', e: '🌵', u: 'кактус' },
      { w: 'rose', e: '🌹', u: 'троянда' },
      { w: 'snowman', e: '⛄', u: 'сніговик' },
    ],
  },
  {
    id: 'toys', name: 'Toys & Games', icon: '🧸', color: '#7cb342',
    words: [
      { w: 'ball', e: '⚽', u: "м'яч" },
      { w: 'basketball', e: '🏀', u: 'баскетбол' },
      { w: 'kite', e: '🪁', u: 'повітряний змій' },
      { w: 'drum', e: '🥁', u: 'барабан' },
      { w: 'guitar', e: '🎸', u: 'гітара' },
      { w: 'piano', e: '🎹', u: 'піаніно' },
      { w: 'robot', e: '🤖', u: 'робот' },
      { w: 'dice', e: '🎲', u: 'гральний кубик' },
      { w: 'puzzle', e: '🧩', u: 'пазл' },
      { w: 'balloon', e: '🎈', u: 'повітряна кулька' },
      { w: 'gift', e: '🎁', u: 'подарунок' },
      { w: 'trophy', e: '🏆', u: 'кубок' },
      { w: 'medal', e: '🏅', u: 'медаль' },
      { w: 'violin', e: '🎻', u: 'скрипка' },
      { w: 'trumpet', e: '🎺', u: 'труба' },
      { w: 'skateboard', e: '🛹', u: 'скейтборд' },
      { w: 'bowling', e: '🎳', u: 'боулінг' },
      { w: 'teddybear', e: '🧸', u: 'плюшевий ведмедик' },
    ],
  },
];

if (typeof module !== 'undefined') module.exports = { THEMES };
